version: '3.9'

services:
  dev-db:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

name: greenlight-development
