###
GET http://localhost:4000/v1/movies?page=100
Accept: application/json

###
POST localhost:4000/v1/users
Content-Type: application/json

{
  "name": "Alice Smith",
  "email": "alice@example.com",
  "password": "pa55word"
}

###

POST localhost:4000/v1/users
Content-Type: application/json

{
  "name": "Bob5 Be",
  "email": "bob5@example.com",
  "password": "pa55word"
}

###
PUT localhost:4000/v1/users/activated
Content-Type: application/json

{
  "token": "SEI367CH4KKWPFA3HOBLWNPXXQ"
}

###
POST localhost:4000/v1/tokens/authentication
Content-Type: application/json

{
  "email": "bob5@example.com",
  "password": "pa55word"
}

###
GET localhost:4000/v1/healthcheck
Content-Type: application/json
Authorization: Bearer SBBYFBM53YSTD6VLERBG7Z3EAQ